### ISSUE TITLE
Data file

### ISSUE THREAD

**Issue by Krimatoria** [MehVahdJukaar/mysticaloaktree-multi#17]
Mystical Oak Tree 1.19.2-1.10 

[28���.2023 22:37:16.005] [Worker-ResourceReload-0/ERROR] [net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener/]: Couldn't parse data file mysticaloaktree:talked193 from mysticaloaktree:tree_wisdom/talked193.json
com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 6 column 6 path $.text[1]
	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:512) ~[client-1.19.2-20220805.130853-srg.jar%23591!/:?]
	at net.minecraft.util.GsonHelper.m_13776_(GsonHelper.java:549) ~[client-1.19.2-20220805.130853-srg.jar%23591!/:?]
	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:43) ~[client-1.19.2-20220805.130853-srg.jar%23591!/:?]
	at net.mehvahdjukaar.mysticaloaktree.client.TreeLoreManager.m_5944_(TreeLoreManager.java:40) ~[mysticaloaktree-1.19.2-1.10.jar%23503!/:?]
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[client-1.19.2-20220805.130853-srg.jar%23591!/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated array at line 6 column 6 path $.text[1]
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562) ~[gson-2.8.9.jar%23127!/:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:475) ~[gson-2.8.9.jar%23127!/:?]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:413) ~[gson-2.8.9.jar%23127!/:?]
	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:675) ~[gson-2.8.9.jar%23127!/:?]
	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:684) ~[gson-2.8.9.jar%23127!/:?]
	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:655) ~[gson-2.8.9.jar%23127!/:?]
	at com.google.gson.internal.bind.TypeAdapters$33$1.read(TypeAdapters.java:866) ~[gson-2.8.9.jar%23127!/:?]
	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:510) ~[client-1.19.2-20220805.130853-srg.jar%23591!/:?]
	... 11 more

**Comment by DeCoded-Void** [comment]
[Found an issue with this file](https://github.com/MehVahdJukaar/mysticaloaktree-multi/blob/ff39e62cfb654d7d943303c8e7a5fffb118e5009/common/src/main/resources/assets/mysticaloaktree/tree_wisdom/talked193.json#L4). The mod isnt working for me either

**Comment by MehVahdJukaar** [comment]
you sure it isnt working? the mod is made so even if one of those has some typos it will still load the rest and just ignore it

**Comment by DeCoded-Void** [comment]
Unsure why, but I haven't gotten any trees to spawn until I patched the file and repackaged it, even when modifying the rarity value.

**Comment by MehVahdJukaar** [comment]
That's just coincidence. They are very rare

**Comment by Krimatoria** [comment]
It works for me, I've seen them) I just sent the logs to you)
